version: '3'
services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://sonarqube_db:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
      - SONARQUBE_JDBC_USERNAME=${SONARQUBE_DB_USERNAME}
      - SONARQUBE_JDBC_PASSWORD=${SONARQUBE_DB_PASSWORD}
    depends_on:
      - sonarqube_db
    links:
      - sonarqube_db
  sonarqube_db:
    image: mysql
    environment:
      - MYSQL_DATABASE=${SONARQUBE_DATABASE}
      - MYSQL_ROOT_PASSWORD=${SONARQUBE_ROOT_PASSWORD}
      - MYSQL_USER=${SONARQUBE_DB_USERNAME}
      - MYSQL_PASSWORD=${SONARQUBE_DB_PASSWORD}
